server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "basket.groupid"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.blomo.api.adapters.kafka.basket.deserializer.ProtoMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.blomo.infrastructure.adapters.kafka.serializer.ProtoMessageSerializer
    template:
      default-topic: "order.status.changed"
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery?currentSchema=delivery
    username: username
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 10
  liquibase:
    default-schema: delivery


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.blomo: debug

application:
  infrastructure:
    grpc:
      host: localhost
      port: 5004
